// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL1hKuWV_wY1jyq-q7xo5Z-A4pM_99Wr8',
    appId: '1:116807904572:web:7bd4ec955d650c3aa34239',
    messagingSenderId: '116807904572',
    projectId: 'examiapp-4a318',
    authDomain: 'examiapp-4a318.firebaseapp.com',
    storageBucket: 'examiapp-4a318.appspot.com',
    measurementId: 'G-EJNYKPME9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwbp25h37NFnwjKLZzzYJaCrQcLqv2cA',
    appId: '1:116807904572:android:c9c59ced6273d2cda34239',
    messagingSenderId: '116807904572',
    projectId: 'examiapp-4a318',
    storageBucket: 'examiapp-4a318.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtotaLUQsn-oRwTLNukkvARAUgbhc6vw',
    appId: '1:116807904572:ios:8eded827fc9273b8a34239',
    messagingSenderId: '116807904572',
    projectId: 'examiapp-4a318',
    storageBucket: 'examiapp-4a318.appspot.com',
    iosBundleId: 'com.example.examiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGtotaLUQsn-oRwTLNukkvARAUgbhc6vw',
    appId: '1:116807904572:ios:b2ac9c4685bbe3c1a34239',
    messagingSenderId: '116807904572',
    projectId: 'examiapp-4a318',
    storageBucket: 'examiapp-4a318.appspot.com',
    iosBundleId: 'com.example.examiapp.RunnerTests',
  );
}
